"""add import tracking tables

Revision ID: 1f67d838840f
Revises: be95a0c1b74a
Create Date: 2026-05-19 21:39:34.277168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f67d838840f'
down_revision: Union[str, Sequence[str], None] = 'be95a0c1b74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('games_found', sa.Integer(), nullable=False),
    sa.Column('games_created', sa.Integer(), nullable=False),
    sa.Column('games_updated', sa.Integer(), nullable=False),
    sa.Column('games_skipped', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_id'), 'import_runs', ['id'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_id'), 'import_errors', ['id'], unique=False)
    op.create_index(op.f('ix_import_errors_import_run_id'), 'import_errors', ['import_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_errors_import_run_id'), table_name='import_errors')
    op.drop_index(op.f('ix_import_errors_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_import_runs_id'), table_name='import_runs')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
